<?php

namespace ContainerNxJ3VRe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y6HEagService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Y6_HEag' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Y6_HEag'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'hoursRepository' => ['privates', 'App\\Repository\\OpeningHoursRepository', 'getOpeningHoursRepositoryService', true],
            'restoRepository' => ['privates', 'App\\Repository\\RestaurantRepository', 'getRestaurantRepositoryService', true],
        ], [
            'hoursRepository' => 'App\\Repository\\OpeningHoursRepository',
            'restoRepository' => 'App\\Repository\\RestaurantRepository',
        ]);
    }
}
