<?php

namespace ContainerNxJ3VRe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EiVABgtService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.EiVABgt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EiVABgt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'menu' => ['privates', '.errored..service_locator.EiVABgt.App\\Entity\\Menu', NULL, 'Cannot autowire service ".service_locator.EiVABgt": it needs an instance of "App\\Entity\\Menu" but this type has been excluded in "config/services.yaml".'],
        ], [
            'doctrine' => '?',
            'menu' => 'App\\Entity\\Menu',
        ]);
    }
}
