<?php

namespace ContainerNxJ3VRe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAllergyRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\AllergyRepository' shared autowired service.
     *
     * @return \App\Repository\AllergyRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AllergyRepository'] = new \App\Repository\AllergyRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
