<?php

namespace ContainerNxJ3VRe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHoursComponentService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Components\HoursComponent' autowired service.
     *
     * @return \App\Components\HoursComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->factories['service_container']['App\\Components\\HoursComponent'] = function () use ($container) {
            return new \App\Components\HoursComponent(($container->privates['App\\Repository\\OpeningHoursRepository'] ?? $container->load('getOpeningHoursRepositoryService')));
        };

        return $container->factories['service_container']['App\\Components\\HoursComponent']();
    }
}
