<?php

namespace ContainerNxJ3VRe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOpeningHoursService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.pf_lk_O.App\Entity\OpeningHours' shared service.
     *
     * @return \App\Entity\OpeningHours
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.pf_lk_O": it needs an instance of "App\\Entity\\OpeningHours" but this type has been excluded in "config/services.yaml".');
    }
}
