<?php

namespace ContainerNxJ3VRe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_TwigComponent_ComponentFactoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'ux.twig_component.component_factory' shared service.
     *
     * @return \Symfony\UX\TwigComponent\ComponentFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->privates['ux.twig_component.component_factory'])) {
            return $container->privates['ux.twig_component.component_factory'];
        }

        return $container->privates['ux.twig_component.component_factory'] = new \Symfony\UX\TwigComponent\ComponentFactory(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            '_hoursComponent' => [false, 'App\\Components\\HoursComponent', 'getHoursComponentService', true],
        ], [
            '_hoursComponent' => 'App\\Components\\HoursComponent',
        ]), ($container->privates['property_accessor'] ?? $container->load('getPropertyAccessorService')), $a, ['_hoursComponent' => ['key' => '_hoursComponent', 'expose_public_props' => true, 'attributes_var' => 'attributes', 'service_id' => 'App\\Components\\HoursComponent', 'class' => 'App\\Components\\HoursComponent', 'template' => 'components/_hoursComponent.html.twig']]);
    }
}
