<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNxJ3VRe\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNxJ3VRe/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerNxJ3VRe.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerNxJ3VRe\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerNxJ3VRe\App_KernelProdContainer([
    'container.build_hash' => 'NxJ3VRe',
    'container.build_id' => '527283e0',
    'container.build_time' => 1678789991,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNxJ3VRe');
