<?php

namespace ContainerFSpnhCo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D86f_AjService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.d86f.Aj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d86f.Aj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dish' => ['privates', '.errored..service_locator.d86f.Aj.App\\Entity\\Dish', NULL, 'Cannot autowire service ".service_locator.d86f.Aj": it needs an instance of "App\\Entity\\Dish" but this type has been excluded in "config/services.yaml".'],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'pictureService' => ['privates', 'App\\Service\\PictureService', 'getPictureServiceService', true],
        ], [
            'dish' => 'App\\Entity\\Dish',
            'doctrine' => '?',
            'pictureService' => 'App\\Service\\PictureService',
        ]);
    }
}
