<?php

namespace ContainerFSpnhCo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Yy5cnkuService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.yy5cnku' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yy5cnku'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'category' => ['privates', '.errored..service_locator.yy5cnku.App\\Entity\\Category', NULL, 'Cannot autowire service ".service_locator.yy5cnku": it needs an instance of "App\\Entity\\Category" but this type has been excluded in "config/services.yaml".'],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'category' => 'App\\Entity\\Category',
            'doctrine' => '?',
        ]);
    }
}
