<?php

namespace ContainerFSpnhCo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAllergyTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\AllergyType' shared autowired service.
     *
     * @return \App\Form\AllergyType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\AllergyType'] = new \App\Form\AllergyType();
    }
}
