<?php

namespace ContainerFSpnhCo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEditProfileFormTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\EditProfileFormType' shared autowired service.
     *
     * @return \App\Form\EditProfileFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\EditProfileFormType'] = new \App\Form\EditProfileFormType();
    }
}
