<?php

namespace ContainerFSpnhCo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEditAllergyFormTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\EditAllergyFormType' shared autowired service.
     *
     * @return \App\Form\EditAllergyFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\EditAllergyFormType'] = new \App\Form\EditAllergyFormType();
    }
}
