<?php

namespace ContainerFSpnhCo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchDishTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\SearchDishType' shared autowired service.
     *
     * @return \App\Form\SearchDishType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\SearchDishType'] = new \App\Form\SearchDishType();
    }
}
