<?php

namespace ContainerKQhtxgh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1EwWNAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1EwW_nA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1EwW_nA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'restaurant' => ['privates', '.errored..service_locator.1EwW_nA.App\\Entity\\Restaurant', NULL, 'Cannot autowire service ".service_locator.1EwW_nA": it needs an instance of "App\\Entity\\Restaurant" but this type has been excluded in "config/services.yaml".'],
        ], [
            'doctrine' => '?',
            'restaurant' => 'App\\Entity\\Restaurant',
        ]);
    }
}
