<?php

namespace ContainerKQhtxgh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5Ap4bXnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5Ap4bXn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5Ap4bXn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dish' => ['privates', '.errored..service_locator.5Ap4bXn.App\\Entity\\Dish', NULL, 'Cannot autowire service ".service_locator.5Ap4bXn": it needs an instance of "App\\Entity\\Dish" but this type has been excluded in "config/services.yaml".'],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'dish' => 'App\\Entity\\Dish',
            'doctrine' => '?',
        ]);
    }
}
