<?php

namespace ContainerKQhtxgh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMenuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.EiVABgt.App\Entity\Menu' shared service.
     *
     * @return \App\Entity\Menu
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.EiVABgt": it needs an instance of "App\\Entity\\Menu" but this type has been excluded in "config/services.yaml".');
    }
}
