<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2N4Bx3f\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2N4Bx3f/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2N4Bx3f.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2N4Bx3f\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2N4Bx3f\App_KernelDevDebugContainer([
    'container.build_hash' => '2N4Bx3f',
    'container.build_id' => 'f790535b',
    'container.build_time' => 1679062848,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2N4Bx3f');
