<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTtxGxqD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTtxGxqD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTtxGxqD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTtxGxqD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTtxGxqD\App_KernelDevDebugContainer([
    'container.build_hash' => 'TtxGxqD',
    'container.build_id' => 'bf06e577',
    'container.build_time' => 1679157336,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTtxGxqD');
